# 1 Importing Libraries

In [223]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


#2 İmporting the Dataset

In [224]:
path = '/content/drive/MyDrive/Machine Learning A-Z (Codes and Datasets)/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Python/Data.csv'
df = pd.read_csv(path)

In [225]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

With this database we have the dependent variable ( Purchased) and the independent variables ( Country, Age, Salary)

In [226]:
X = df.iloc[:,:-1].to_numpy()
y = df.iloc[:,-1:].to_numpy()

We need the X and y variable as an array to feed into machine learning models. So we used pandas.DataFrame.To_numpy() to get the array from a Data Frame.

I will attache these nvery nice explanation from a course that i took. 

For those of you interested in following the Python tutorials of this course, here is a short summary of what you need to know in Object-oriented programming. In the Python tutorials, I will be talking about classes, objects and methods. Please find below a clear explanation of what these concepts are:

A class is the model of something we want to build. For example, if we make a house construction plan that gathers the instructions on how to build a house, then this construction plan is the class.

An object is an instance of the class. So if we take that same example of the house construction plan, then an object is simply a house. A house (the object) that was built by following the instructions of the construction plan (the class).

And therefore there can be many objects of the same class, because we can build many houses from the construction plan.

A method is a tool we can use on the object to complete a specific action. So in this same example, a tool can be to open the main door of the house if a guest is coming. A method can also be seen as a function that is applied onto the object, takes some inputs (that were defined in the class) and returns some output.




#3 Dealing with the missing data

We have missing datas which we can find easily with pandas.DataFrame.isna() functions. 
As we see there is some missing data on both Age, and Salary columns. 
We decide to fill these datas with scikit learn simple imputer.


In [227]:
df.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [228]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [229]:
from sklearn.impute import SimpleImputer

In [230]:
imputer = SimpleImputer()

In [231]:
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit(X[:,1:3])

X[:,1:3] = imp_mean.transform(X[:,1:3])


#4 Encoding categorical Data

As you can see on country column we have there categories which we need to change with numerical values. 
We can use scikit OneHotEncoder to fix this issue.

**This part is a very important part to understand how to manipulate a categorical data to a numerical data**

In [232]:
from pandas.core.dtypes.cast import ensure_nanosecond_dtype
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
encoder = OneHotEncoder()
ct = ColumnTransformer(transformers=[("encoder", OneHotEncoder(), [0])],remainder='passthrough')

In [233]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [234]:
X = ct.fit_transform(X)

In [235]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

#5 Label Encoding with Scikit

In [236]:
from sklearn.preprocessing import LabelEncoder

In [237]:
le = LabelEncoder()
y = le.fit_transform(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [238]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

#5 Splitting the Data


In [239]:
from sklearn.model_selection import train_test_split

In [240]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [241]:
print(X_train)
print(y_train)
print(X_test)
print(y_test)

[[1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]
[1 0 1 1 0 0]
[[0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 44.0 72000.0]]
[0 1 1 0]


#6 Feature Scaling

We can only apply feature scaling after train test split. Otherwise we affected by test data which is called (Leakage)

We dont need to apply feature scaling to the country columns. (Dummy Variables). İt might increase the performance of the model slightly. but we will lose the connection betweencategories and variables.



Standart Scaler standardize features by removing the mean and scaling to unit variance.

In [242]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [243]:
X_train[:,3:] = scaler.fit_transform(X_train[:,3:])
scaler.n_samples_seen_
X_test[:,3:] = scaler.transform(X_test[:,3:])

**We use just transform instead of fit_transform to prevent data leakege.**

In [244]:
X_train

array([[1.0, 0.0, 0.0, 1.7749251497827823, 1.8147396179442679],
       [0.0, 1.0, 0.0, -1.634614861262403, -0.9851443640268875],
       [1.0, 0.0, 0.0, -0.30868263474483093, 0.4707953065981133],
       [0.0, 1.0, 0.0, 0.25957403376269994, 0.10992137114405362],
       [0.0, 0.0, 1.0, -0.11926374524232065, -0.20117684907496403],
       [0.0, 0.0, 1.0, 0.028062057704076396, -1.20913508258458]],
      dtype=object)

In [245]:
X_test

array([[0.0, 1.0, 0.0, 2.153762928787803, 2.262721055059653],
       [0.0, 0.0, 1.0, -2.2028715297699337, -1.6571165196999649],
       [1.0, 0.0, 0.0, -0.6875204137498515, -0.5371629269115027],
       [1.0, 0.0, 0.0, 1.017249591772741, 1.0307721029923445]],
      dtype=object)

In [251]:
y_train

array([1, 0, 1, 1, 0, 0])

In [252]:
y_test

array([0, 1, 1, 0])

#Notes

These objects( Scaler,le,ct,imputer) are instances of their classes. We can reach atributes of these objects to get more data about these objects. For example we can get standart scalers parameter with .get_param function. or we can modify these objects with set_param...